# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme 

# remote_theme: pages-themes/dinky@v0.2.0
# plugins:
# - jekyll-remote-theme

# theme: minima

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme